apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-3
spec:
  selector:
    matchLabels:
      app: hw-3
  replicas: 1
  template:
    metadata:
      labels:
        app: hw-3
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
